# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190127_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proile',
            name='description',
            field=models.TextField(default='description default text'),
        ),
    ]
