# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-28 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190128_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proile',
            new_name='profile',
        ),
    ]
