# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190128_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='locations',
            field=models.CharField(default='my location default', max_length=120),
        ),
    ]
